### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by LWJerri** [sekkure/picture_client#1]
Hello. I see you create 4 constants where use `useState('');` method in this file: https://github.com/sekkure/picture_client/blob/master/src/pages/Login/index.tsx#L17-L20

Why are you doing it this way and not like this:

```ts
const [name, setName, password, setPassword, etc..] = useState('')
```

**Comment by LWJerri** [comment]
You can remove "`" (backticks) from this line: https://github.com/sekkure/picture_client/blob/master/src/pages/Login/index.tsx#L61

For example - `localStorage.setItem('userId', userData.user.userID)`

**Comment by LWJerri** [comment]
You missed remove `baseURL` - https://github.com/sekkure/picture_client/blob/master/src/app/api/apiSlice.ts#L12

**Comment by LWJerri** [comment]
I think you can make `const {access_token, expires_in} = refreshResult.data as RefreshTokenData` for make code more beautiful and in `setCredentials()` method just provide readt `access_token` and `expires_in`.

https://github.com/sekkure/picture_client/blob/master/src/app/api/apiSlice.ts#L46-L54

**Comment by sekkure** [comment]
> Hello. I see you create 4 constants where use `useState('');` method in this file: https://github.com/sekkure/picture_client/blob/master/src/pages/Login/index.tsx#L17-L20
> 
> Why are you doing it this way and not like this:
> 
> ```ts
> const [name, setName, password, setPassword, etc..] = useState('')
> ```

Didn't know you can do this.

> You can remove "`" (backticks) from this line: https://github.com/sekkure/picture_client/blob/master/src/pages/Login/index.tsx#L61
> 
> For example - `localStorage.setItem('userId', userData.user.userID)`

Will remove this one 👍

> You missed remove `baseURL` - https://github.com/sekkure/picture_client/blob/master/src/app/api/apiSlice.ts#L12

Doesn't get what you mean here 🤔

> I think you can make `const {access_token, expires_in} = refreshResult.data as RefreshTokenData` for make code more beautiful and in `setCredentials()` method just provide readt `access_token` and `expires_in`.
> 
> https://github.com/sekkure/picture_client/blob/master/src/app/api/apiSlice.ts#L46-L54

Yeah why not 👍 #beautifulcode

СПАСИБО ЗА СОВЕТЫ! Толком не пишу фронт, хочу развиваться в этом плане, огромное спасибо
@LWJerri

**Comment by LWJerri** [comment]
> Doesn't get what you mean here 🤔
I mean you forget to remove the NGROK link. Maybe you need to use `.env` or something other. Other people can't use your app correctly, because a link is dead.

**Comment by sekkure** [comment]
Блин, лень писать на английском :D

Да приложение в разработке еще, если нужно кому будет - думаю разберутся и поменяют. Всё таки её нужно только в одном месте сменить (спойлер, нет.)
Я хотел вынести её в `ENV`, но там нужно немного вебпак конфиг поднастроить. А я `react-scripts` использую, и нужно разобраться как `eject` использовать. Пока отложил это на потом.

**Comment by LWJerri** [comment]
> Блин, лень писать на английском :D
> 
> Да приложение в разработке еще, если нужно кому будет - думаю разберутся и поменяют. Всё таки её нужно только в одном месте сменить (спойлер, нет.) Я хотел вынести её в `ENV`, но там нужно немного вебпак конфиг поднастроить. А я `react-scripts` использую, и нужно разобраться как `eject` использовать. Пока отложил это на потом.

Okay, no problem.

**Comment by sekkure** [comment]
Will add `ENV` support in future & first code question seems like weird because typescript doesn't allow me to do
`const [user, setUser, etc...] = useState()`

**Comment by LWJerri** [comment]
> Will add `ENV` support in future & first code question seems like weird because typescript doesn't allow me to do `const [user, setUser, etc...] = useState()`
> 
> And fixed second one question, forget to mention it

Hello. My bad, don't touch `const [user, setUser] = useState(''), etc..`.
